version: '3.9'

services:
  activitywatcher-http:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: activitywatcher-mcp-http
    environment:
      MCP_PORT: ${MCP_PORT:-3000}
      AW_URL: ${AW_URL:-http://host.docker.internal:5600}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    ports:
      - "${MCP_PORT:-3000}:3000"
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          node -e "fetch('http://127.0.0.1:' + (process.env.MCP_PORT || 3000) + '/health').then(r=>{if(r.ok)process.exit(0);process.exit(1);}).catch(()=>process.exit(1));"
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  activitywatcher-stdio:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: activitywatcher-mcp-stdio
    command: ["stdio"]
    stdin_open: true
    tty: true
    environment:
      AW_URL: ${AW_URL:-http://host.docker.internal:5600}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    profiles:
      - stdio
