services:
  activitywatch-mcp-http:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: ghcr.io/auriora/activitywatch-mcp:dev

  activitywatch-mcp-stdio:
    build:
      context: .
      dockerfile: docker/Dockerfiles
    image: ghcr.io/auriora/activitywatch-mcp:dev
