name: Release Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Override version tag (defaults to release tag)'
        required: false
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Resolve version metadata
        id: vars
        shell: bash
        run: |
          set -euo pipefail
          version="${{ github.event.release.tag_name || github.event.inputs.version_tag }}"
          if [[ -z "$version" ]]; then
            echo "::error::No version tag provided" >&2
            exit 1
          fi
          sanitized=${version#v}
          sanitized=$(printf '%s' "$sanitized" | tr '[:upper:]' '[:lower:]')
          repo="${GITHUB_REPOSITORY,,}"
          echo "version=$sanitized" >> "$GITHUB_OUTPUT"
          echo "repository=$repo" >> "$GITHUB_OUTPUT"

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}
            ${{ env.REGISTRY }}/${{ steps.vars.outputs.repository }}:latest
          platforms: linux/amd64

      - name: Publish summary
        if: always()
        run: |
          cat <<'SUMMARY' >> "$GITHUB_STEP_SUMMARY"
          ## Docker Image Published
          - Image: ${{ env.REGISTRY }}/${{ steps.vars.outputs.repository }}
          - Version tag: `${{ steps.vars.outputs.version }}`
          - Additional tag: `latest`
          SUMMARY
